[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/addresses"
  to = "/.netlify/functions/addresses"
  status = 200

[[redirects]]
  from = "/api/collections"
  to = "/.netlify/functions/collections"
  status = 200
